### PR TITLE
Support arguments in throwsException()

### PR DESCRIPTION
**Pull request by endash**
These commits add support for passing arguments to the function being tested. If the argument passed to assert is an array, the function is plucked off of index 0 and the rest of the array is passed as the arguments.

### CODE REVIEW

**Comment by jamesbebbington** [comment]
+1 for this functionality!

**Comment by endash** [comment]
I'm undecided whether simply passing an anonymous function which does the calling is a solution sufficient to render this issue moot

**Comment by endash** [comment]
I'm going to close this because this solution isn't any more elegant than simply wrapping the function call in an anonymous function.

**Comment by endash** [comment]
For anyone who comes across this:

This patch would have allowed an assertion as such:
````assert ([Timber.monthHasDay, 1970, 12, 4]).throwsException();

Instead you can do something like the following:
````assert (function () { Timber.monthHasDay(1970, 12, 4); }).throwsException();

**Comment by jamesbebbington** [comment]
Thanks @endash.

**Pull request closed without merging**
